# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bernard/git/new-ctools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bernard/git/new-ctools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bernard/git/new-ctools/CMakeFiles /home/bernard/git/new-ctools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bernard/git/new-ctools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hexdump.exe

# Build rule for target.
hexdump.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hexdump.exe
.PHONY : hexdump.exe

# fast build rule for target.
hexdump.exe/fast:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/build
.PHONY : hexdump.exe/fast

hexdump/src/file-reader.o: hexdump/src/file-reader.c.o

.PHONY : hexdump/src/file-reader.o

# target to build an object file
hexdump/src/file-reader.c.o:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/file-reader.c.o
.PHONY : hexdump/src/file-reader.c.o

hexdump/src/file-reader.i: hexdump/src/file-reader.c.i

.PHONY : hexdump/src/file-reader.i

# target to preprocess a source file
hexdump/src/file-reader.c.i:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/file-reader.c.i
.PHONY : hexdump/src/file-reader.c.i

hexdump/src/file-reader.s: hexdump/src/file-reader.c.s

.PHONY : hexdump/src/file-reader.s

# target to generate assembly for a file
hexdump/src/file-reader.c.s:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/file-reader.c.s
.PHONY : hexdump/src/file-reader.c.s

hexdump/src/hexdump.o: hexdump/src/hexdump.c.o

.PHONY : hexdump/src/hexdump.o

# target to build an object file
hexdump/src/hexdump.c.o:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/hexdump.c.o
.PHONY : hexdump/src/hexdump.c.o

hexdump/src/hexdump.i: hexdump/src/hexdump.c.i

.PHONY : hexdump/src/hexdump.i

# target to preprocess a source file
hexdump/src/hexdump.c.i:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/hexdump.c.i
.PHONY : hexdump/src/hexdump.c.i

hexdump/src/hexdump.s: hexdump/src/hexdump.c.s

.PHONY : hexdump/src/hexdump.s

# target to generate assembly for a file
hexdump/src/hexdump.c.s:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/hexdump.c.s
.PHONY : hexdump/src/hexdump.c.s

hexdump/src/hexops.o: hexdump/src/hexops.c.o

.PHONY : hexdump/src/hexops.o

# target to build an object file
hexdump/src/hexops.c.o:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/hexops.c.o
.PHONY : hexdump/src/hexops.c.o

hexdump/src/hexops.i: hexdump/src/hexops.c.i

.PHONY : hexdump/src/hexops.i

# target to preprocess a source file
hexdump/src/hexops.c.i:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/hexops.c.i
.PHONY : hexdump/src/hexops.c.i

hexdump/src/hexops.s: hexdump/src/hexops.c.s

.PHONY : hexdump/src/hexops.s

# target to generate assembly for a file
hexdump/src/hexops.c.s:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/hexdump/src/hexops.c.s
.PHONY : hexdump/src/hexops.c.s

lib/src/clist.o: lib/src/clist.c.o

.PHONY : lib/src/clist.o

# target to build an object file
lib/src/clist.c.o:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/lib/src/clist.c.o
.PHONY : lib/src/clist.c.o

lib/src/clist.i: lib/src/clist.c.i

.PHONY : lib/src/clist.i

# target to preprocess a source file
lib/src/clist.c.i:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/lib/src/clist.c.i
.PHONY : lib/src/clist.c.i

lib/src/clist.s: lib/src/clist.c.s

.PHONY : lib/src/clist.s

# target to generate assembly for a file
lib/src/clist.c.s:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/lib/src/clist.c.s
.PHONY : lib/src/clist.c.s

lib/src/rbuffer.o: lib/src/rbuffer.c.o

.PHONY : lib/src/rbuffer.o

# target to build an object file
lib/src/rbuffer.c.o:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/lib/src/rbuffer.c.o
.PHONY : lib/src/rbuffer.c.o

lib/src/rbuffer.i: lib/src/rbuffer.c.i

.PHONY : lib/src/rbuffer.i

# target to preprocess a source file
lib/src/rbuffer.c.i:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/lib/src/rbuffer.c.i
.PHONY : lib/src/rbuffer.c.i

lib/src/rbuffer.s: lib/src/rbuffer.c.s

.PHONY : lib/src/rbuffer.s

# target to generate assembly for a file
lib/src/rbuffer.c.s:
	$(MAKE) -f CMakeFiles/hexdump.exe.dir/build.make CMakeFiles/hexdump.exe.dir/lib/src/rbuffer.c.s
.PHONY : lib/src/rbuffer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hexdump.exe"
	@echo "... hexdump/src/file-reader.o"
	@echo "... hexdump/src/file-reader.i"
	@echo "... hexdump/src/file-reader.s"
	@echo "... hexdump/src/hexdump.o"
	@echo "... hexdump/src/hexdump.i"
	@echo "... hexdump/src/hexdump.s"
	@echo "... hexdump/src/hexops.o"
	@echo "... hexdump/src/hexops.i"
	@echo "... hexdump/src/hexops.s"
	@echo "... lib/src/clist.o"
	@echo "... lib/src/clist.i"
	@echo "... lib/src/clist.s"
	@echo "... lib/src/rbuffer.o"
	@echo "... lib/src/rbuffer.i"
	@echo "... lib/src/rbuffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

